### ISSUE TITLE
Fix minifb related performance issues on macOS

### ISSUE THREAD

**Issue by jovobe** [LukasKalbertodt/mahboi#29]
The crate minifb has some issues on macOS. Due to that the maximum frame rate that can be achieved is about 50 fps.

**Comment by LukasKalbertodt** [comment]
Related: https://github.com/emoon/rust_minifb/issues/28

**Comment by LukasKalbertodt** [comment]
I think we should switch to an OpenGL window (using `glium` and `winit`) in the long run:

- Probably fixes this issue
- We get way more accurate and detailed event information via `winit` (in particular, controllers)
- If we want to implement some kind of upscaling, we could do that via shader which is probably a lot faster

**Comment by LukasKalbertodt** [comment]
#46 Switched from `minifb` to `pixels` which works completely different. So I am pretty sure this issue is solved or outdated.
